import Vue from 'vue'
import colors from 'vuetify/lib/util/colors'
import Vuetify, {
    VAppBarNavIcon,
    VAlert,
    VApp,
    VAppBar,
    VAutocomplete,
    VAvatar,
    VBadge,
    VBanner,
    VBottomNavigation,
    VBottomSheet,
    VBreadcrumbs,
    VBtn,
    VBtnToggle,
    VCalendar,
    VCard,
    VCarousel,
    VCheckbox,
    VChip,
    VChipGroup,
    VCol,
    VColorPicker,
    VCombobox,
    VContent,
    VCounter,
    VData,
    VDataIterator,
    VDataTable,
    VDatePicker,
    VDialog,
    VDivider,
    VExpansionPanel,
    VFileInput,
    VFooter,
    VForm,
    VHover,
    VIcon,
    VImg,
    VInput,
    VItemGroup,
    VLabel,
    VLazy,
    VList,
    VMain,
    VMenu,
    VMessages,
    VNavigationDrawer,
    VOtpInput,
    VOverflowBtn,
    VOverlay,
    VPagination,
    VParallax,
    VPicker,
    VProgressCircular,
    VProgressLinear,
    VRadioGroup,
    VRangeSlider,
    VRating,
    VResponsive,
    VRow,
    VSelect,
    VSheet,
    VSkeletonLoader,
    VSlideGroup,
    VSlider,
    VSnackbar,
    VSparkline,
    VSpeedDial,
    VStepper,
    VSubheader,
    VSwitch,
    VSystemBar,
    VTab,
    VTabs,
    VTabItem,
    VTabsItems,
    VTextarea,
    VTextField,
    VThemeProvider,
    VTimeline,
    VTimePicker,
    VToolbar,
    VTooltip,
    VTreeview,
    VVirtualScroll,
    VWindow,
    VListItem,
    VListItemIcon,
    VListItemContent,
    VListItemTitle,
    VListItemSubtitle,
    VToolbarTitle,
    VContainer,
    VSpacer,
    VItem,
    VCardText,
    VCardActions,
    VCardTitle,
    VCardSubtitle,
    VToolbarItems,
} from 'vuetify/lib'

Vue.use(Vuetify, {
    components: {
        VAppBarNavIcon,
        VAlert,
        VApp,
        VAppBar,
        VAutocomplete,
        VAvatar,
        VBadge,
        VBanner,
        VBottomNavigation,
        VBottomSheet,
        VBreadcrumbs,
        VBtn,
        VBtnToggle,
        VCalendar,
        VCard,
        VCarousel,
        VCheckbox,
        VChip,
        VChipGroup,
        VCol,
        VColorPicker,
        VCombobox,
        VContent,
        VCounter,
        VData,
        VDataIterator,
        VDataTable,
        VDatePicker,
        VDialog,
        VDivider,
        VExpansionPanel,
        VFileInput,
        VFooter,
        VForm,
        VHover,
        VIcon,
        VImg,
        VInput,
        VItemGroup,
        VLabel,
        VLazy,
        VList,
        VMain,
        VMenu,
        VMessages,
        VNavigationDrawer,
        VOtpInput,
        VOverflowBtn,
        VOverlay,
        VPagination,
        VParallax,
        VPicker,
        VProgressCircular,
        VProgressLinear,
        VRadioGroup,
        VRangeSlider,
        VRating,
        VResponsive,
        VRow,
        VSelect,
        VSheet,
        VSkeletonLoader,
        VSlideGroup,
        VSlider,
        VSnackbar,
        VSparkline,
        VSpeedDial,
        VStepper,
        VSubheader,
        VSwitch,
        VSystemBar,
        VTab,
        VTabs,
        VTabItem,
        VTabsItems,
        VTextarea,
        VTextField,
        VThemeProvider,
        VTimeline,
        VTimePicker,
        VToolbar,
        VTooltip,
        VTreeview,
        VVirtualScroll,
        VWindow,
        VListItem,
        VListItemIcon,
        VListItemContent,
        VListItemTitle,
        VListItemSubtitle,
        VToolbarTitle,
        VContainer,
        VSpacer,
        VItem,
        VCardText,
        VCardActions,
        VCardTitle,
        VCardSubtitle,
        VToolbarItems,
    }
})

export default new Vuetify({
    icons: {
        iconfont: 'mdi' // 'md' || 'mdi' || 'mdiSvg' || 'md' || 'fa' || 'fa4'
    },
    theme: {
        dark: false,

        themes: {
            light: {
                primary: colors.lightGreen.lighten1,
                secondary: colors.grey.darken1,
                accent: colors.shades.black,
                error: colors.red.accent3
            },
            dark: {
                primary: colors.blueGrey.lighten3
            }
        }
    }
})
